### ISSUE TITLE
Component unmount does not stop video

### ISSUE THREAD

**Issue by gregogalante** [davichoso/react-native-video360#4]
Hi, first of all I would like to congratulate you on having created a library like this.

I'm working with an Android real device with:
"react-native": "0.63.4"
"react-native-video360plugin": "^1.0.6"

I have a situation similar to this:

```js
function ParentComponent() {
  const [video, setVideo] = useState(false)
  return (
   <>
    <TouachableOpacity onPress={() => setVideo(!video)}>
       <Text>Toggle video</Text>
   </TouachableOpacity>
   {video && <VideoComponent />}
   </>
  )
}

function VideoComponent() {
  return (
   <Video360 urlVideo={'https://.......mp4'} modeVideo={1} style={{ flex: 1}} />
  )
}
```

When i tap the button for the second time the VideoComponent is unmounted but the audio of the video continue to play in background mode.
The audio continue to running also after a refresh of the application and it stops only when i close the application.
When i tap the button again I watch a new video with the audio of the before execution in background (so with two audio at the same time)

**Comment by gregogalante** [comment]
I have found a solution to stop the previous video when is running the new one by this edit:

```java
// Video360Module.java

@Override
    protected View createViewInstance(ThemedReactContext context) {
        if (view != null) { // Shutdown old video if it is present
            view.pauseRendering();
            view.shutdown();
        }

        view = new VrVideoView(context.getCurrentActivity());
        view.setEventListener(new VideoActivityEventListener());

        return view;
    }
```

However it doesn't stop the video when i unmount the component. Do you know a way to get the unmount event on the Java code?

**Comment by davichoso** [comment]
great
